---
- name: provision ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/aws.yml
    - vars/vault.yml

  tasks:
    - import_tasks: tasks/ec2.yml

- name: install and configure jenkins on ec2 instance
  hosts: launched
  gather_facts: false
  remote_user: ec2-user
  connection: ssh
  become: yes

  tasks: 
    - import_tasks: tasks/jenkins.yml

- name: tear down aws environment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/aws.yml
    - vars/vault.yml

  tasks:
    - import_tasks: tasks/destroy.yml
      when: destroy | bool